# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI - Test storybook

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    working-directory: ./front-end

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies...
      run: yarn install

    - name: Generate storybook... 🚀
      run: yarn run build-storybook

    - name: Deploy storybook... 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: front-end/storybook-static # The folder that the build-storybook script generates files.
        clean: true # Automatically remove deleted files from the deploy branch

